- name: Demonstrates dictionary variable and its navigation
  hosts: localhost
  vars:
    - contacts:
         Sriram:
           name: Sriram Jeganathan
           mobile: 123-456-8900
         Nitesh:
             name: Nitesh Jegannathan
             mobile: 343-453-5642
  tasks:
    - name: print all contacts
      debug: msg="Mobile number of {{item.value.name}} is {{item.value.mobile}}."
      with_dict: "{{contacts}}"

# Key is Nitesh. item.value.name is name
