    - name: Restart nginx web server on Ubuntu
      service: name=nginx state=restarted
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

    - name: Restart nginx web server on CentOS
      shell: service nginx restart
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

